### ISSUE TITLE
Setup CD pipeline for web

### ISSUE THREAD

**Issue by Wadeewee** [nimblehq/showcase-flutter-build-web-desktop#27]
## Why

We need to set up a `CD` pipeline to achieve this outcome

>  Deploy the web version to a simple hosting site where it can be accessible by non-engineers.

## Who Benefits?

Developers

**Comment by luongvo** [comment]
@Wadeewee @markgravity I just had a quick discussion with Andy, I think we should consider deploying the web version as `HTML renderer` instead of `CanvasKit renderer` https://docs.flutter.dev/platform-integration/web/renderers#choosing-which-option-to-use 🤔

**Comment by markgravity** [comment]
@luongvo got it, I will set up to build it as `HTML` 🙏

**Comment by luongvo** [comment]
One thing that we should ensure building as HTML only for web.

**Comment by luongvo** [comment]
@markgravity or maybe find a way to deploy in both renderers than we can have the base to make comparison and see the issues https://www.reddit.com/r/FlutterDev/comments/10ix09l/flutter_web_canvaskit_or_html_renderer/
